# Generated by Django 4.1.6 on 2023-02-14 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_librarian_managers_librarian_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
        migrations.AddField(
            model_name='booksd',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 14, 7, 52, 678052)),
        ),
        migrations.AlterField(
            model_name='booksd',
            name='issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 14, 14, 7, 52, 678052)),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='password',
            field=models.CharField(max_length=1255),
        ),
    ]
