# Generated by Django 4.1.6 on 2023-02-16 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_booksd_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='booksd',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 45, 13, 152804)),
        ),
        migrations.AlterField(
            model_name='booksd',
            name='issued',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 2, 16)),
        ),
    ]
